### ISSUE TITLE
What should I do if I want to break the commit or push when pytest result is failed?

### ISSUE THREAD

**Issue by scottming** [ygpedroso/python-githooks#1]
Could you give me an example?

**Comment by ygpedroso** [comment]
> Could you give me an example?

If what you want is to bypass the execution of the hooks when you are committing the code, you can do it by simply running `git commit --no-verify` or `git commit -n`, that should do the trick.

Otherwise, I am not sure if I fully understood your question, can you be more specific?
Glad to be of help.

**Comment by scottming** [comment]
@ygpedroso Forgive me, English is not my mother language. 

My questing is: when I do commit:

```bash
_common.py                  84 ERROR    Exception serializing message!
Traceback (most recent call last):
  File "/Users/scottming/.local/share/virtualenvs/omc-rgitserver-lBNF_2KV/lib/python3.7/site-packages/grpc/_common.py", line 82, in _transform
    return transformer(message)
TypeError: descriptor 'SerializeToString' for 'google.protobuf.pyext._message.CMessage' objects doesn't apply to 'NoneType' object
------------------------------------------------------ Captured stdout teardown -------------------------------------------------------
Testing files was removed!

---------- coverage: platform darwin, python 3.7.2-final-0 -----------
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
omc_rgitserver/serviers/file_servicer.py      24      0   100%
omc_rgitserver/serviers/repo_servicer.py      28      0   100%
--------------------------------------------------------------
TOTAL                                         52      0   100%

================================================= 1 failed, 14 passed in 2.65 seconds =================================================
[develop bef1d82] githooks test
 1 file changed, 1 insertion(+), 1 deletion(-)
```
The above code shows `pytest` result have 1 failed, and the `git commit` is success.

I want the `pytest` and `git-commit` both success or both failed.

**Comment by ygpedroso** [comment]
> @ygpedroso Forgive me, English is not my mother language.
> 
> My questing is: when I do commit:
> 
> ```shell
> _common.py                  84 ERROR    Exception serializing message!
> Traceback (most recent call last):
>   File "/Users/scottming/.local/share/virtualenvs/omc-rgitserver-lBNF_2KV/lib/python3.7/site-packages/grpc/_common.py", line 82, in _transform
>     return transformer(message)
> TypeError: descriptor 'SerializeToString' for 'google.protobuf.pyext._message.CMessage' objects doesn't apply to 'NoneType' object
> ------------------------------------------------------ Captured stdout teardown -------------------------------------------------------
> Testing files was removed!
> 
> ---------- coverage: platform darwin, python 3.7.2-final-0 -----------
> Name                                       Stmts   Miss  Cover
> --------------------------------------------------------------
> omc_rgitserver/serviers/file_servicer.py      24      0   100%
> omc_rgitserver/serviers/repo_servicer.py      28      0   100%
> --------------------------------------------------------------
> TOTAL                                         52      0   100%
> 
> ================================================= 1 failed, 14 passed in 2.65 seconds =================================================
> [develop bef1d82] githooks test
>  1 file changed, 1 insertion(+), 1 deletion(-)
> ```
> 
> The above code shows `pytest` result have 1 failed, and the `git commit` is success.
> 
> I want the `pytest` and `git-commit` both success or both failed.

@scottming I just deployed version `1.0.6` of the library, which should provide the behaviour you are expecting.
Please let me know if it works ok for you.
Glad to be of help.

**Comment by scottming** [comment]
@ygpedroso Hi, Yannier, I've installed the version 1.0.6 and test. It works very well. Thank you for your work.

**Comment by ygpedroso** [comment]
> @ygpedroso Hi, Yannier, I've installed the version 1.0.6 and test. It works very well. Thank you for your work.

Great.
